[workspace]
members = [
    "cherry-core",
    "cherry-render",
    "cherry-backend-raster",
    "cherry-backend-ray",
    "cherry-app",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
image = "0.25"
nalgebra = "0.34.1"
rand = "0.10"
rayon = "1.11"
