pub mod camera;
pub mod color;
pub mod frame;
pub mod intersection;
pub mod light;
pub mod material;
pub mod math;
pub mod primitive;
pub mod ray;
pub mod scene;

pub use camera::Camera;
pub use color::Color;
pub use frame::FrameRequest;
pub use intersection::Hit;
pub use light::Light;
pub use material::{Lambertian, Material};
pub use primitive::{Cuboid, Primitive, Sphere};
pub use ray::Ray;
pub use scene::{SceneProvider, SceneSnapshot, StaticSceneProvider};
